# Generated by Django 5.1.5 on 2025-02-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variations',
            old_name='Product',
            new_name='product',
        ),
    ]
