# Generated by Django 5.1.5 on 2025-02-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_categories_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='showinmenu',
            field=models.BooleanField(default=True),
        ),
    ]
